### ISSUE TITLE
cannot build the project...

### ISSUE THREAD

**Issue by christian130** [Persei08/butter-desktop#4]
Operating System Version:
windows 7 32 bit

Popcorn Time Version:
@latest

Download date:
april 29th, 2018 at 15:30 (-4 GMT)

Expected Behaviour
Generate the binaries...

Actual Behaviour
C:/~/popforntime\popcorn-desktop>gulp build
[19:10:02] Using gulpfile ~\popforntime\popcorn-desktop\gulpfile.js
[19:10:02] Starting 'build'...
[19:10:02] Starting 'injectgit'...
Branch: development
Commit: f381d44
[19:10:02] Finished 'injectgit' after 42 ms
[19:10:02] Starting 'css'...
Stylus files compiled in G:~\popforntime\popcorn-deskt
src\app\themes
[19:10:04] Finished 'css' after 2.62 s
[19:10:04] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.9.1
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.

npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0

at ChildProcess.exithandler (child_process.js:275:12)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on (internal/child_process.js:346:11)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at Pipe._handle.close [as _onclose] (net.js:567:12)
killed: false,
code: 1,
signal: null,
cmd: 'npm ls --production=true --parseable=true' }
[19:10:08] Finished 'nwjs' after 3.5 s
[19:10:08] Finished 'build' after 6.17 s

Steps to reproduce the behaviour
What steps do we need to take to find the same bug that you found?

...npm install
...bower install
...gulp build
npm version is
G:~\popforntime\3>node -v
v8.11.1
G:~\popforntime\3>npm -v
5.6.0

**Comment by christian130** [comment]
please PM me for giving you more details...

**Comment by Persei08** [comment]
Ok, i just saw, it's not my branch. I don't provide help here for popcorn-official branchs. They have their one repo

**Comment by christian130** [comment]
the bug is also printing in your code...

**Comment by christian130** [comment]
i then go to node_modules folder and then to node-pre-gyp and then into it i hit a git clone and npm link or a npm install directly...

**Comment by Persei08** [comment]
>the bug is also printing in your code...
Yeah, I understanded in other issue.

>i then go to node_modules folder and then to node-pre-gyp and then into it i hit a git clone and npm link or a npm install directly...

I don't undesrtand, What do you mean by "I then go to node_modules folder" ? I don't touch node_modules, npm deal with that.

**Comment by christian130** [comment]
that's what i thought... but it's giving some sort of dependencies
"unsatisfied"... i also use the npm install --save, and nothing... it's
weird because i've build several times this app in others windows
distributions and no problem...
i think is the npm that is messing up with the dependencies...
the command
npm ls --production=true --parseable=true
is messing around with ALL the modules INSIDE the node_modules folder...
and goes one by one checking into it's package.json, and it seems that in
deed one of the dependencies named  node-pre-gyp doesnt have the
node_modules i mean is bad constructed and the folder node_modules is quite
empty and it's package.json says that it REQUIRE mkdirp and so on...

---------- Forwarded message ----------

**Comment by christian130** [comment]
if npm deals with that then it have to really satisfy the dependencies
which are in the dependencies package.json part
when i did hit npm install doesnt work
i think if we create a postscript or something...

**Comment by christian130** [comment]
but the dependency tree is not bad constructed... it's good enough, because i also installed globally the dependencies using a script 
@echo off
start npm install -g mkdirp@0.5.1

start npm install -g minimist@0.0.8

start npm install -g minimatch@3.0.4
start npm install -g brace-expansion@1.1.11
start npm install -g balanced-match@1.0.0
start npm install -g concat-map@0.0.1
start npm install -g console-control-strings@1.1.0
start npm install -g inherits@2.0.3
start npm install -g safe-buffer@5.1.1
start npm install -g safe-buffer@5.1.1
start npm install -g console-control-strings@1.1.0
start npm install -g string-width@1.0.2
start npm install -g strip-ansi@3.0.1
start npm install -g code-point-at@1.1.0
start npm install -g is-fullwidth-code-point@1.0.0
start npm install -g strip-ansi@3.0.1
start npm install -g number-is-nan@1.0.1
start npm install -g ansi-regex@2.1.1
start npm install -g string-width@1.0.2
start npm install -g inherits@2.0.3
start npm install -g minimatch@3.0.4
start npm install -g once@1.4.0
start npm install -g once@1.4.0
start npm install -g wrappy@1.0.2
start npm install -g wrappy@1.0.2
start npm install -g minipass@2.2.4
start npm install -g mkdirp@0.5.1
start npm install -g safe-buffer@5.1.1
start npm install -g yallist@3.0.2
start npm install -g minipass@2.2.4
start npm install -g safe-buffer@5.1.1
start npm install -g yallist@3.0.2

**Comment by Persei08** [comment]
try that: 
- gulp clean
- npm install -g bower gulp
- npm install
- bower install
- gulp build
- gulp run

if it don't work something is wrong with your dev environement

**Comment by christian130** [comment]
- gulp clean -> OK
   - npm install -g bower gulp -> OK
   - npm install -> OK
   - bower install -> OK
   - gulp build -> FAILED
   - gulp run ->FAILED

doesnt matter what i try... also if i upgrade to the latest version of
npm it doesnt pass even in the npm install

**Comment by christian130** [comment]
https://pastebin.com/tVc62kC1

**Comment by christian130** [comment]
http://zipansion.com/E4Ua

**Comment by Persei08** [comment]
https://nodejs.org/dist/latest-v7.x/
