### ISSUE TITLE
npm ls --production=true --parseable=true

### ISSUE THREAD

**Issue by christian130** [Persei08/butter-desktop#5]
everything start with this
i've got build it using the multifix branch

**Comment by christian130** [comment]
i did some modifications... but i think it's the npm node version that is causing this because i've just installed the new version and cannot even launch it the npm install ... it failed...
when i got into the node_modules and the node-pre-gyp folder... i hit a npm link (and he construct again the required dependencies...)
the versions of the packages are OK... maybe it would be by modifying the package.json and adding a script to do so before npm install is executed in the process i dont know...

**Comment by christian130** [comment]
this bug only works if the production flag is enabled... if not it will just go after it...

**Comment by Persei08** [comment]
I use node 7.10.1 and npm 4.2.0 on ubuntu 16.04. If it's related to your other issue (#4), you're not in the right place, use their issue tracker.

If multifix branch, please provide logs. and technical details

**Comment by christian130** [comment]
i also launch the code using your master forked version and still giving me the error using the prod flag...
seems that the command
npm ls --production=true --parseable=true
is giving some errors and therefore the gulpfile in this part: 
const parseReqDeps = () => {
    return new Promise((resolve, reject) => {
        exec('npm ls --prod=true --parseable=true', {maxBuffer: 1024 * 500}, (error, stdout, stderr) => {
            if (error || stderr) {
                reject(error || stderr);
            } else {
                // build array
                let npmList = stdout.split('\n');

                // remove empty or soon-to-be empty
                npmList = npmList.filter((line) => {
                    return line.replace(process.cwd().toString(), '');
                });

                // format for nw-builder
                npmList = npmList.map((line) => {
                    return line.replace(process.cwd(), '.') + '/**';
                });

                // return
                resolve(npmList);
            }
        });
    });
};
the dependencies in the production and dev are OK... when you go to the properly repo and make a npm link for example...

**Comment by christian130** [comment]
i have a log file but how i'm trying to give it to you personal... through
PM

**Comment by christian130** [comment]
windows 7 32 bits
https://expirebox.com/download/cc3063d3be83c067edb3492a6768348d.html

**Comment by Persei08** [comment]
my master branch is just butter-desktop branch I don't provide support for it.
I cannot see your file, it ask a password... 
why you just dont copy paste it or provide a pastebin link ?

**Comment by christian130** [comment]
download it again...

https://expirebox.com/download/7cebd5aed80ab90db400dbba7d228230.html

**Comment by christian130** [comment]
if you cannot download the link i'll supply you with a special
pastebin file... but in the mean while you can try to download the link i
just sent you

**Comment by Persei08** [comment]
Yeah, I have downloaded your files.

I don't see why it's a big deal to copy paste them : 

```
[23:30:20] Using gulpfile ~\Desktop\popforntime\fuck\butter-desktop\gulpfile.js
[23:30:20] Starting 'build'...
[23:30:20] Starting 'injectgit'...
Branch: HEAD
Commit: 14160f40
[23:30:20] Finished 'injectgit' after 31 ms
[23:30:20] Starting 'css'...
Stylus files compiled in G:\Users\Christian\Desktop\popforntime\fuck\butter-desktop\src\app\themes\
[23:30:22] Finished 'css' after 2.68 s
[23:30:22] Starting 'nwjs'...
[23:30:26] Finished 'nwjs' after 3.86 s
[23:30:26] Finished 'build' after 6.57 s
```

So finally it said Finished 'build" after 6.57s,

**Comment by christian130** [comment]
it says finished and after that comes the error i gave you... the thing
about the command

**Comment by christian130** [comment]
this THING... can be fixed by changing the gulp.js line 
>>> ls --production=true --parseable=true
for this
```
ls --dev=true
```
